/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutInfo {
  'bio' : string,
  'socialLinks' : Array<SocialLink>,
  'profilePhotoUrl' : string,
}
export type ContactId = bigint;
export interface ContactInput {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface ContactSubmission {
  'id' : ContactId,
  'name' : string,
  'read' : boolean,
  'email' : string,
  'message' : string,
  'timestamp' : Timestamp,
}
export interface Project {
  'id' : ProjectId,
  'techTags' : Array<string>,
  'title' : string,
  'order' : bigint,
  'description' : string,
  'sourceUrl' : string,
  'imageUrl' : string,
  'visible' : boolean,
  'liveUrl' : string,
}
export type ProjectId = bigint;
export interface ProjectInput {
  'techTags' : Array<string>,
  'title' : string,
  'order' : bigint,
  'description' : string,
  'sourceUrl' : string,
  'imageUrl' : string,
  'visible' : boolean,
  'liveUrl' : string,
}
export interface SocialLink {
  'url' : string,
  'title' : string,
  'icon' : string,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'addProject' : ActorMethod<[ProjectInput], Project>,
  'deleteProject' : ActorMethod<[ProjectId], boolean>,
  'getAbout' : ActorMethod<[], [] | [AboutInfo]>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getProject' : ActorMethod<[ProjectId], [] | [Project]>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'initOwner' : ActorMethod<[], boolean>,
  'isOwner' : ActorMethod<[], boolean>,
  'markContactRead' : ActorMethod<[ContactId], boolean>,
  'submitContact' : ActorMethod<[ContactInput], ContactSubmission>,
  'updateAbout' : ActorMethod<[string, Array<SocialLink>], undefined>,
  'updateProfilePhoto' : ActorMethod<[string], undefined>,
  'updateProject' : ActorMethod<[ProjectId, ProjectInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];