/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProjectInput = IDL.Record({
  'techTags' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'description' : IDL.Text,
  'sourceUrl' : IDL.Text,
  'imageUrl' : IDL.Text,
  'visible' : IDL.Bool,
  'liveUrl' : IDL.Text,
});
export const ProjectId = IDL.Nat;
export const Project = IDL.Record({
  'id' : ProjectId,
  'techTags' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'description' : IDL.Text,
  'sourceUrl' : IDL.Text,
  'imageUrl' : IDL.Text,
  'visible' : IDL.Bool,
  'liveUrl' : IDL.Text,
});
export const SocialLink = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'icon' : IDL.Text,
});
export const AboutInfo = IDL.Record({
  'bio' : IDL.Text,
  'socialLinks' : IDL.Vec(SocialLink),
  'profilePhotoUrl' : IDL.Text,
});
export const ContactId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ContactSubmission = IDL.Record({
  'id' : ContactId,
  'name' : IDL.Text,
  'read' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
});
export const ContactInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProject' : IDL.Func([ProjectInput], [Project], []),
  'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
  'getAbout' : IDL.Func([], [IDL.Opt(AboutInfo)], ['query']),
  'getContactSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], []),
  'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'initOwner' : IDL.Func([], [IDL.Bool], []),
  'isOwner' : IDL.Func([], [IDL.Bool], ['query']),
  'markContactRead' : IDL.Func([ContactId], [IDL.Bool], []),
  'submitContact' : IDL.Func([ContactInput], [ContactSubmission], []),
  'updateAbout' : IDL.Func([IDL.Text, IDL.Vec(SocialLink)], [], []),
  'updateProfilePhoto' : IDL.Func([IDL.Text], [], []),
  'updateProject' : IDL.Func([ProjectId, ProjectInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProjectInput = IDL.Record({
    'techTags' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'description' : IDL.Text,
    'sourceUrl' : IDL.Text,
    'imageUrl' : IDL.Text,
    'visible' : IDL.Bool,
    'liveUrl' : IDL.Text,
  });
  const ProjectId = IDL.Nat;
  const Project = IDL.Record({
    'id' : ProjectId,
    'techTags' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'description' : IDL.Text,
    'sourceUrl' : IDL.Text,
    'imageUrl' : IDL.Text,
    'visible' : IDL.Bool,
    'liveUrl' : IDL.Text,
  });
  const SocialLink = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'icon' : IDL.Text,
  });
  const AboutInfo = IDL.Record({
    'bio' : IDL.Text,
    'socialLinks' : IDL.Vec(SocialLink),
    'profilePhotoUrl' : IDL.Text,
  });
  const ContactId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ContactSubmission = IDL.Record({
    'id' : ContactId,
    'name' : IDL.Text,
    'read' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const ContactInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addProject' : IDL.Func([ProjectInput], [Project], []),
    'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
    'getAbout' : IDL.Func([], [IDL.Opt(AboutInfo)], ['query']),
    'getContactSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], []),
    'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'initOwner' : IDL.Func([], [IDL.Bool], []),
    'isOwner' : IDL.Func([], [IDL.Bool], ['query']),
    'markContactRead' : IDL.Func([ContactId], [IDL.Bool], []),
    'submitContact' : IDL.Func([ContactInput], [ContactSubmission], []),
    'updateAbout' : IDL.Func([IDL.Text, IDL.Vec(SocialLink)], [], []),
    'updateProfilePhoto' : IDL.Func([IDL.Text], [], []),
    'updateProject' : IDL.Func([ProjectId, ProjectInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };